### ISSUE TITLE
Error when running react-native link

### ISSUE THREAD

**Issue by miguelHx** [jigsawxyz/react-native-coreml-image#4]
I used react-native-init to create my project.
My package.json file:
```
{
  "name": "project name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-core-ml-image": "0.0.6"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

When I run the ```react-native link``` command, I get the following error:

```
module.js:550
    throw err;
    ^

Error: Cannot find module 'asap/raw'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (project/node_modules/promise/lib/core.js:3:12)
    at Module._compile (module.js:653:30)
    at Module._compile (project/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (project/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:566:32)
```

Any idea why this might be the case?

**Comment by darylrowland** [comment]
Hi, that doesn’t look like an issue with the CoreML module as we don’t have a dependency on anything called asap/raw.

I suspect it must be an issue with one of the other modules you have included
